networks:
  app-net:

volumes:
  postgres_data:

services:
  # PostgreSQL (internal)
  postgres:
    image: postgres:15-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net
    # No ports published in prod

  # Quarkus Backend (internal)
  quarkus-service:
    build:
      context: ./quarkus-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: auth-quarkus
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/authdb
      QUARKUS_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JAVA_OPTS: "-Xmx256m -Xms128m"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-net

  # Node.js Proxy (internal)
  node-proxy:
    build:
      context: ./node-proxy
    container_name: auth-node
    environment:
      QUARKUS_URL: http://quarkus-service:8080
      SESSION_SECRET: ${SESSION_SECRET:?set-a-strong-secret}
      NODE_ENV: production
      NODE_OPTIONS: --max-old-space-size=128
    depends_on:
      quarkus-service:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-net

  # React + Nginx (public)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Frontend calls same-origin /api; Nginx should proxy /api -> node-proxy:3000
        - REACT_APP_API_URL=/api
    container_name: auth-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      node-proxy:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-net
