version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  quarkus-service:
    build:
      context: ./quarkus-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: auth-quarkus
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/authdb
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_HTTP_CORS_ORIGINS=http://localhost:3000
      - JAVA_OPTS=-Xmx256m -Xms128m
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 320M
        reservations:
          memory: 256M

  nodejs-proxy:
    build:
      context: ./nodejs-proxy
    container_name: auth-nodejs
    environment:
      - QUARKUS_URL=http://quarkus-service:8080/api
      - SESSION_SECRET=production-secret-key-change-me-min-32-chars
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=128
    ports:
      - "3001:3000"
    depends_on:
      - quarkus-service
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 192M
        reservations:
          memory: 128M

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:3001/api
    container_name: auth-frontend
    ports:
      - "80:80"
    depends_on:
      - nodejs-proxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
